### ISSUE TITLE
Narzędzie do streamingu

### ISSUE THREAD

**Issue by erykpiast** [meetjspl/online#1]
Trzeba jakoś połączyć prelegentów z uczestnikami :)

Wymagania
 * pozwala współdzielić ekran
 * klient na Windows, Linux i MacOS (może być web!)
 * podział na organizatorów, prelegentów i uczestników
 * pomieści kilkaset osób

Nice to have
 * wbudowany czat do zadawania pytań
 * mordka prezentującego wyświetlana razem z treścią ekranu

Wstępne propozycje
 * [ ] [CrowdCast](https://www.crowdcast.io/)
 * [ ] [Jami](http://jami.net/)

**Comment by naugtur** [comment]
OSB Studio + twitch działa bez zarzutu.

**Comment by erykpiast** [comment]
Na meetup listopadowy będziemy mieć narzędzie do webinarów od sponosora. Jak już będę wiedział co to, wpiszę.

**Comment by erykpiast** [comment]
[ClickMeeting](https://clickmeeting.com/) sprawdził się okej, możemy tego używać jeżeli sponsor nie będzie mieć swojego narzędzia.
