### ISSUE TITLE
A/B testing and canary releases - why, what and how? The engineer's perspective on A/B testing and sending conversion rate to the moon 🚀 

### ISSUE THREAD

**Issue by rrhubarb** [meetjspl/online#10]
Hi,

my name is Rafal and I have 6 years of experience in developing SaaS platforms as a frontend engineer. As someone who likes data, statistics and most importantly - product development - I'd like to share my thoughts on what I perceive as a crucial part of product engineering.

Main title: A/B testing and canary releases - why, what, and how?
Subtitle: The engineer's perspective on A/B testing and sending the conversion rate to the moon 🚀 

I'd like to give a talk in which I'd describe my thoughts and experience with A/B testing (more business-oriented cases) and canary releases (more development-oriented cases). The presentation will include:
1. An answer to what A/B testing and canary releases are.
2. Insight on why you should give it a try as having the option for percentage rollouts and being data-driven is beneficial to literally everyone.
3. A list of tools that proved to be helpful for different scenarios and their alternatives I know of.
4. Examples of tests I came up with that turned out to be successful (or a disaster) as well as cases where it saved my company a considerable amount of money.
5. Information on how to tackle the problem of having insufficient data to make the right decisions as early as possible by introducing correct statistical models.
6. Ideas of what you can try to experiment with and where to look for inspiration and knowledge. 
7. Last but not least - GME related memes. Cause _I like stock_.

I can give this talk either in Polish or English based on your preference.

To confirm I exist (as I don't have much activity on my personal GH account) here's my LI profile https://www.linkedin.com/in/rafalrumanek/

Thanks,
Rafal

**Comment by naugtur** [comment]
Mocny temat!
Dorzucisz jakieś doświadczenia w robieniu softu tak, żeby dało się praktykować canary release?
Chociaż w sumie nie wiem czy to się zmieści w półgodzinnej prezentacji. Już jest sporo materiału.

**Comment by rrhubarb** [comment]
Dzięki!

Planowałem opowiedzieć o tym jak można zorganizować proces developomentu ze zwróceniem uwagi gdzie powinno pomyśleć się o pewnych decyzjach (np. togglowanie i możliwość % rolloutu) na przykładzie m. in. takich historii jak:
- konieczne przerobienie nawigacji w produkcie - jak nie wkurzyć wszystkich klientów na raz tylko ewentualnie tych, którzy są przyzwyczajeni do testowania i zgłosili się do produktowego laba, a po znęcaniu się tej partii użytkowników, poprawieniu tego co mieliśmy w sentry, zauważyliśmy za pomocą analityki i dowiedzieliśmy się bezpośrednio od użytkowników, stopniowym wypuszczaniu do większej grupy (przesuwając tylko suwak w odpowiednim narzędziu) i ponownym przechodzeniu przez ww. kroki,
- sytuacji, w której dość inwazyjne zmiany zostały wprowadzone od razu do wszystkich a na nieszczęście zawierały jeszcze dość sporego buga, którego nie wyłapaliśmy. Robiąc canary release przynajmniej ograniczylibyśmy szkody,
- operowania na nie do końca testowalnych w syntetycznym środowisku kawałkach systemu jakim są płatności (i różne banki oraz karty) przy wprowadzaniu wsparcia dla 3D-Secure 2.0 i jak nas uratowało to, że mieliśmy czas i możliwość obserwowania ewentualnych niedopatrzeń,
- ...i jak uczynić z takiego podejścia normę z uwzględnieniem rozmiarów zadań, wpływu na użytkownika i oceny ryzyk.

W tym wszystkim oczywiście kilka słów jak przykładowo można zarządzać kodem, jakie narzędzia można wykorzystać a jednocześnie jaki jest koszt takiego podejścia.

Nie będą to oczywiście bardzo dogłębne case study, bo tak jak wspomniałeś czas będzie ograniczał, ale postaram się wyciągnąć esencję. Wszelkie sugestie oczywiście mile widziane!

**Comment by erykpiast** [comment]
@trutniov Super temat! Chciałbyś go zaprezentować pod koniec kwietnia? :)

**Comment by erykpiast** [comment]
Wielkie dzięki za prezentację! Podlinkujesz tu slajdy, @trutniov? :)

**Comment by rrhubarb** [comment]
Dzięki za możliwość wystąpienia!
https://slides.com/rafalrumanek-truti/deck-8419d4/
