### ISSUE TITLE
Podstawy wizualizacji danych

### ISSUE THREAD

**Issue by adrianmroz** [meetjspl/online#3]
Prezentacja o wizualizacji danych w przeglądarce. Najpierw krótkie wytłumaczenie co to wizualizacja i po co to robimy, a potem z pomocą Grammar of Graphics pokażę jak zrobić prostą i trochę bardziej skomplikowaną wizualizację w React z użyciem d3.js.

**Comment by erykpiast** [comment]
A ja chciałbym usłyszeć coś o https://airbnb.io/visx/. Nie jakieś wprowadzenie do biblioteki, bo to wtórne, ale Twoją opinię jako osoby, która pracuje z Reactem i D3. Mogę liczyć na coś takiego?

**Comment by adrianmroz** [comment]
Nie pasuje mi to idealnie do tematu ale zahaczę na tyle, żebyś mógł mnie zaskoczyć takim pytaniem na koniec.

**Comment by erykpiast** [comment]
Super prezentacja! Ogromne dzięki. Wrzucisz tutaj slajdy @adrianmroz ? :)

**Comment by adrianmroz** [comment]
Proszę, [dataviz101.pdf](https://github.com/meetjspl/online/files/5968260/dataviz101.pdf)
