### ISSUE TITLE
Wprowadzenie do string literals types w TypeScript 4.1

### ISSUE THREAD

**Issue by MichalZalecki** [meetjspl/online#4]
Cześć!

Zarys

- szybkie wprowadzenie do typowania
- podstawowe zastosowanie template literals type
- co ciekawsze zastosowania (np. JSON parser, querySelector)
- omówienie zaawansowanego przykładu

**Comment by erykpiast** [comment]
Zastanawiam się, czy takie typy da się użyć w tak zwanej codziennej pracy, czy raczej tylko jako twórca biblioteki. Czy przewidujesz takie przykłady w "podstawowe zastosowania template literals type"? :)

**Comment by MichalZalecki** [comment]
Tak, w drugiej "kropce" chciałbym pokazać właśnie coś takiego.

**Comment by erykpiast** [comment]
@MichalZalecki super prezentacja! Nie miałeś łatwego zadania, to była trudna wiedza do przekazania :D Wrzuć tutaj proszę swoje slajdy :)

**Comment by MichalZalecki** [comment]
@erykpiast Dzięki za organizację! 👏 

Slajdy: https://bit.ly/template-literals-slides
