### ISSUE TITLE
React Suspense - czy warto korzystać już dziś?

### ISSUE THREAD

**Issue by patrykomiotek** [meetjspl/online#5]
Czy warto korzystać z React Suspense i w jakich obszarach może ułatwić nam pracę?
W trakcie prezentacji opowiem:
* jaka jest idea stojąca ze Suspense
* do czego możę się przydać w kontekście pracy z asynchronicznymi zasobami
* czy warto wprowadzać już teraz Suspense do projektów opartych na React.js

**Comment by erykpiast** [comment]
Będzie o code splitingu i dynamicznych importach komponentów? :)

**Comment by patrykomiotek** [comment]
tak, też się pojawi :)

**Comment by erykpiast** [comment]
Hej @patrykomiotek! Wielkie dzięki za prezentację :) Załącz tutaj proszę link lub plik ze slajdami. Pamiętaj też o linku do CodeSandbox!

**Comment by patrykomiotek** [comment]
Hej, materiały:

* [prezka](https://speakerdeck.com/patrykomiotek/meet-dot-js-online-number-1)
* kodzik:
  * [Simple data fetching](https://codesandbox.io/s/01-simple-data-fetching-xhlmk)
  * [Fetching with Error Boundaries](https://codesandbox.io/s/02-simple-data-fetching-witch-error-boundary-z72ih)
  * [Resources and fetching](https://codesandbox.io/s/03-simple-data-fetching-create-resource-hm2sf )
