### ISSUE TITLE
Tailwind CSS - a utility-first CSS framework

### ISSUE THREAD

**Issue by wittek** [meetjspl/online#6]
Tutaj Adrian z Sonalake. Poproszono mnie o dodanie propozycji tematu prezentacji.

Chciałbym pokazać bibliotekę tailwind css i opisać moje doświadczenia z używania jej w jednym z naszych projektów. Zagadnienia, które chciałbym poruszyć:
- czym różni się "utility-first CSS framework" od bibliotek takich jak bootstrap czy bulma
- odniesienie się do częstego pytania - "w czym jest to lepsze od inline styli?"
- krótki rys historyczny Atomic / Utility-First CSS - główne założenia, poprzednie rozwiązania, dlaczego tailwind jest aktualnie najpopularniejszą biblioteką z tego trendu
- live coding z implementacją prostego komponentu w trakcie którego chciałbym pokazać setup i kilka narzędzi z community (PurgeCSS, wizualizacja konfiguracji, plugin do vscode)
- opis moich doświadczeń z tailwind w prawdziwym projekcie

**Comment by erykpiast** [comment]
Świetnie, dzięki za dodanie zgłoszenia! Agenda wygląda zachęcająco :)

Jeżeli mogę coś poradzić w kwestii live codingu: https://blog.jayway.com/2015/03/30/using-git-commits-to-drive-a-live-coding-session/ @naugtur może pewnie rozwinąć ten pomysł, wiem, że go stosuje :) Odchodzi wtedy sporo stresu, że coś przestanie działać w ostatniej chwili albo że jakieś trudne do zauważenia typo zepsuje cały flow prezentacji.

**Comment by naugtur** [comment]
Mam do tego narzędzie. Podlinkuje w nocy :)

**Comment by erykpiast** [comment]
Bardzo dziękujemy za fajną prezentację! Sądząc po liczbie pytań zainteresowanie było duże :) Wrzucisz tutaj proszę link do slajdów @wittek?

**Comment by wittek** [comment]
@erykpiast Proszę: https://docs.google.com/presentation/d/1fibhvDhXo5S-7QRxTp1DrOjnFyZaVeHZRCri6QwLeK8/edit?usp=sharing :) 
Dla wygody tutaj jeszcze w PDF: [Tailwind CSS.pdf](https://github.com/meetjspl/online/files/5971307/Tailwind.CSS.pdf)
