### ISSUE TITLE
Big gestures - My experiments to learn tough programming concepts at 10x speed

### ISSUE THREAD

**Issue by gitcommitshow** [meetjspl/online#7]
It is about an experiment I did in 2020 to learn some tough subjects (advanced javascript, modular maths, cryptography,
encryption, etc.) in a short time-frame(2 weeks). This talk will help any developer "learn more effectively" using the similar kind of framework I have figured out or at least inspire to create your own framework.

**Comment by erykpiast** [comment]
Big thanks for the speech! If you could, please link/upload the deck here :)
