### ISSUE TITLE
Module Federation - jedna aplikacja z wielu niezależnych buildów

### ISSUE THREAD

**Issue by MichalZalecki** [meetjspl/online#8]
Cześć,

**Konspekt**

Pracując nad złożonymi aplikacjami w zespołach, które odpowiadają za różne części domeny dostrzegamy związane z tym wyzwania jak zachowanie zwinności procesu, współdzielenie kodu, integracja, prędkość developmentu, wdrożeń jak i wydajność/rozmiar samej aplikacji. W odpowiedzi na te i podobne problemy jako społeczność coraz częściej wybieramy monorepo czy eksperymentujemy z micro-frontends.

Webpack Module Federation ma pozwolić nam w prosty sposób podzielić aplikację w taki sposób by jej poszczególne elementy mogły być niezależnie budowane i osobno wdrażane.

**Agenda**

_Plan prezentacji jest jeszcze mocno roboczy. Wczesny feedback mile widziany!_

* Wprowadzenie do **Module Federation**
* Rozbicie przykładowej aplikacji na **monorepo z użyciem lerna**
* Konfiguracja Module Federation na potrzeby SPA
* **Niezależny build** poszczególnych części aplikacji

**Comment by erykpiast** [comment]
Super byłoby pokazać jakie są opcje developmentu poszczególnych części takiej aplikacji. Myślę o "preview na localhoscie" oraz testach.

Inna rzecz: jak wygląda routing? Czy ładując `myapp.com/foo` ściągniemy inny kod niż w przypadku wejścia na `myapp.com/bar`? Tylko ten potrzebny do załadowania konkretnej strony? Jeżeli tak się da, czy dostajemy to w pakiecie, czy musimy sami skleić jakieś klocki w odpowiedniej kolejności?

Tak czy inaczej, super temat. Na czasie :)

**Comment by erykpiast** [comment]
Super prezentacja, dzięki! Wrzucisz tu slajdy, @MichalZalecki?

**Comment by MichalZalecki** [comment]
Dzięki @erykpiast! Link do slajdów: http://bit.ly/meetjs4-slajdy

**Comment by derekqq** [comment]
@MichalZalecki czy prezentacja jest gdzieś nagrana?

**Comment by erykpiast** [comment]
Hej @derekqq, tak :) https://www.youtube.com/watch?v=4WeuVz9l3JQ
