### ISSUE TITLE
GraphQL jako alternatywa dla REST API

### ISSUE THREAD

**Issue by RafalPydyniak** [meetjspl/online#9]
Cześć!

Podczas prezentacji chciałbym wprowadzić słuchaczy do tematu GraphQL jako alternatywy dla standardowego REST API. Przede wszystkim chciałbym pokazać:

- Czym jest
- Jakie problemy próbuje rozwiązać - w nawiązaniu do RESTa
- Zalety/wady obu rozwiązań i kiedy warto rozważyć wybór jednego a kiedy drugiego

Będzie trochę kodu, ale nie będzie jakiegoś bardzo długiego live codingu (szczególnie, że podobno lepiej tego unikać na tych spotkaniach online)

Prezentacja tak naprawdę nie wymaga zbyt wiele od uczestników, Na pewno więcej wyniosą z niej osoby, które wiedzą czym jest REST, ale nawet to nie jest wymogiem.

**Comment by RafalPydyniak** [comment]
Jeżeli ktoś przypadkiem szukał prezentacji to zostawiam tutaj. Z lekkim opóźnieniem, ale zawsze :)
[GraphQL.pptx](https://github.com/meetjspl/online/files/6212238/GraphQL.pptx)

**Comment by erykpiast** [comment]
Dzięki za prezentację! :)
